### ISSUE TITLE
Setting reward issue

### ISSUE THREAD

**Issue by kimbring2** [YuhangSong/Arena-BuildingToolkit#19]
Hello,

I am following a 'Tutorials: Building Toolkit' but blocked at reward setting part of '[Get Started 3] Create a Simple Two Players Game' video.

![reward](https://user-images.githubusercontent.com/11064407/73265995-5c659c00-4219-11ea-9084-9fd16e55c73b.png)
As you can see in attacthed image, my reward setting menu is little different from tutorial video.
How can I set a rewerd for agent at this menu like a tutorial video?

Thank you

**Comment by YuhangSong** [comment]
Hi,

Yes, the project has been updated since we made the video to support more general settings. And we have been short of hands to update the documentation, I sincerely apologize. Do consider help us with the documentation if you are interested/

In your case, since you are building two player's game, in the tutorial, the two agents are competitive, thus, you need to look at the section of "reward function (competitive)".

By checking "is reward ranking", you enable this competitive reward function. It means the agent under this node that survive longer gets a higher reward. You may take a look at the game under GameSets/Tennis/2T1P as an example.

Let me know if you have further questions.

We are adding more helping tips to the code and please keep updating to the recent commits of the repo.

**Comment by kimbring2** [comment]
Oh, thank you for your kindness.

Do not need to apologize. I know how difficult it is to keep all documents up to date. 
I can solve a reward issue based on your advice and another video.

P.S.
I read the Arena paper carefully and agree that Arena can replace an existing, old and simple research environment. I also tried to use a Malmo and DeepMind Lab. However, both of them require much time for using. Thus, I want to contribute to Arena project on the line I can for developing more convenient RL research tool.

Thank you,
Dohyeong

**Comment by YuhangSong** [comment]
Hi,

Thanks for your interest. We are indeed at a stage where we have lots of items on the TODO list and seeking people to join us. Please follow the links provided on the home page to join us in Slack first, message me there and I will get you in an internal channel will we intensively discuss our progress and new features. (currently, there are just two including me working on the project, and you are much welcomed to join)

And Arena project will be continuously maintained and developed as I myself will keep using it as the base of my future research. Also, there are tons of new features that are already there but have not been documented yet. We are discussing the best way to document things and one of the major next steps, for now, is to make documents. Nevertheless, there are tons of ideas in the todo and backlog list (see the Trello page, the link of which can also be found on the home page).

Looking forward to your joining.
